PLAYER_SCHEMA = {
    "definitions": {},
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://example.com/object1685148430.json",
    "title": "Root",
    "type": "object",
    "required": ["player_name", "player_country", "timestamp", "player_level", "player_os", "score"],
    "properties": {
        "player_name": {
            "$id": "#root/player_name",
            "title": "Player_name",
            "type": "string",
            "default": "",
            "examples": ["PLAYER Alex"],
            "pattern": "^.*$",
        },
        "player_country": {
            "$id": "#root/player_country",
            "title": "Country",
            "type": "string",
            "default": "",
            "examples": ["Brazil"],
            "pattern": "^.*$",
        },
        "player_level": {
            "$id": "#root/player_level",
            "title": "Level",
            "type": "string",
            "default": "",
            "examples": ["L1"],
            "pattern": "^.*$",
        },
        "player_os": {
            "$id": "#root/player_os",
            "title": "Os",
            "type": "string",
            "default": "",
            "examples": ["Android"],
            "pattern": "^.*$",
        },
        "score": {
            "$id": "#root/score",
            "title": "Score",
            "type": "integer",
            "examples": [3],
            "default": 0,
        },
        "timestamp": {
            "$id": "#root/score",
            "title": "Score",
            "type": "string",
            "examples": [3],
            "default": 0,
        },
    },
}
