PLAYER_SCHEMA = {
    "definitions": {},
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://example.com/object1685148430.json",
    "title": "Root",
    "type": "object",
    "required": ["player_name", "country", "timestamp", "level", "os", "score"],
    "properties": {
        "player_name": {
            "$id": "#root/player_name",
            "title": "Player_name",
            "type": "string",
            "default": "",
            "examples": ["PLAYER Alex"],
            "pattern": "^.*$",
        },
        "country": {
            "$id": "#root/country",
            "title": "Country",
            "type": "string",
            "default": "",
            "examples": ["Brazil"],
            "pattern": "^.*$",
        },
        "level": {
            "$id": "#root/level",
            "title": "Level",
            "type": "string",
            "default": "",
            "examples": ["L1"],
            "pattern": "^.*$",
        },
        "os": {
            "$id": "#root/os",
            "title": "Os",
            "type": "string",
            "default": "",
            "examples": ["Android"],
            "pattern": "^.*$",
        },
        "score": {
            "$id": "#root/score",
            "title": "Score",
            "type": "integer",
            "examples": [3],
            "default": 0,
        },
        "timestamp": {
            "$id": "#root/score",
            "title": "Score",
            "type": "integer",
            "examples": [3],
            "default": 0,
        },
    },
}
